name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Add any other architectures or OS versions you'd like to build for

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: Build project
      run: |
        mkdir build
        cd build
        qmake ..
        make

    - name: upload darwin artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/azblogfilter.darwin-amd64.tar.gz
        asset_name: my-artifact-${{ matrix.os }}
        asset_content_type: application/gzip
